pub mod agent_program;
pub mod agents;
pub mod app;
pub mod attention;
pub mod buttons;
mod command;
pub mod config;
pub mod control;
pub mod corral;
pub mod diagnostics;
pub mod git;
pub mod history;
pub mod input;
pub mod kitty;
mod launch;
pub mod layout;
pub mod layout_state;
pub mod mascot;
pub mod placement;
pub mod pty;
pub mod search;
pub mod settings;
pub mod terminal;
pub mod terminals;
pub mod ui;
pub mod updates;
pub mod viewer;

pub mod theme;
